import type { Metadata } from "next";
import {Roboto, Poppins, Playfair_Display, JetBrains_Mono, Fira_Code, Ma_Shan_Zheng } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/layout/Footer";

const roboto = Roboto ({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const poppins = Poppins ({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: "400",
});

const playfairDisplay = Playfair_Display ({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});


const jetBrainsMono = JetBrains_Mono ({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
  weight: "400",
});

const firaCode = Fira_Code ({
  subsets: ["latin"],
  variable: "--font-fira-code",
  display: "swap",
  weight: "400",
});

const maShanZheng = Ma_Shan_Zheng ({
  subsets: ["latin"],
  variable: "--font-ma-shan-zheng",
  display: "swap",
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable} 
          ${poppins.variable} 
          ${playfairDisplay.variable} 
          ${jetBrainsMono.variable} 
          ${firaCode.variable} 
          ${maShanZheng.variable}
          antialiased`
        }
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
